spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:h2:mem:dbtest
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 12
      # 空闲时保持最小连接数
      minimum-idle: 5
      # 空闲连接存活时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 20000
      # 测试sql
      connection-test-query: select 1
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  sql:
    init:
      schema-locations: classpath:datasource/schema.sql
      data-locations: classpath:datasource/data.sql